"""add timestamp columns to each table

Revision ID: 0b9082eb1c5f
Revises: ec444292335a
Create Date: 2021-08-24 08:22:12.806264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b9082eb1c5f"
down_revision = "ec444292335a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goals", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("goals", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("intervals", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("intervals", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("intervals", "updated_at")
    op.drop_column("intervals", "created_at")
    op.drop_column("goals", "updated_at")
    op.drop_column("goals", "created_at")
    # ### end Alembic commands ###
