"""intervals table (related to the goals table in many-to-1 manner)

Revision ID: ec444292335a
Revises: 15652658e0a6
Create Date: 2020-11-06 09:37:19.409378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec444292335a"
down_revision = "15652658e0a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intervals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("final", sa.DateTime(), nullable=True),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("intervals")
    # ### end Alembic commands ###
